CREATE OR REPLACE FUNCTION fun_cancellaBachecheVecchioUtente() RETURNS TRIGGER AS $$
BEGIN
	DELETE FROM BACHECA
	WHERE autore = OLD.username;
	RETURN OLD;
END $$ LANGUAGE PLPGSQL;

CREATE TRIGGER cancellaBachecheVecchioUtente
BEFORE DELETE ON UTENTE
FOR EACH ROW
EXECUTE FUNCTION fun_cancellaBachecheVecchioUtente();